apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 240068248627.dkr.ecr.ap-south-1.amazonaws.com/jenkins-assignment:v1
        ports:
        - containerPort: 8000
       
